[1m========================== test session starts ===========================[0m
platform linux -- Python 3.13.0, pytest-8.3.4, pluggy-1.5.0 -- /home/ymarca/anaconda3/envs/mlflow-2a75d5483ccc955a591f3bf19dd358a7ce61a76f/bin/python3.13
cachedir: .pytest_cache
rootdir: /home/ymarca/Code/music_genre_classification/check_data
collected 0 items / 1 error                                              [0m

================================= ERRORS =================================
[31m[1m_____________________ ERROR collecting test_data.py ______________________[0m
[1m[31mtest_data.py[0m:6: in <module>
    logging.basicConfig(
[1m[31mE   NameError: name 'logging' is not defined. Did you forget to import 'logging'?[0m
[33m============================ warnings summary ============================[0m
../../../anaconda3/envs/mlflow-2a75d5483ccc955a591f3bf19dd358a7ce61a76f/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py:91
  /home/ymarca/anaconda3/envs/mlflow-2a75d5483ccc955a591f3bf19dd358a7ce61a76f/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py:91: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    _EPOCH_DATETIME_NAIVE = datetime.datetime.utcfromtimestamp(0)

../../../anaconda3/envs/mlflow-2a75d5483ccc955a591f3bf19dd358a7ce61a76f/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py:195
../../../anaconda3/envs/mlflow-2a75d5483ccc955a591f3bf19dd358a7ce61a76f/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py:195
../../../anaconda3/envs/mlflow-2a75d5483ccc955a591f3bf19dd358a7ce61a76f/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py:195
  /home/ymarca/anaconda3/envs/mlflow-2a75d5483ccc955a591f3bf19dd358a7ce61a76f/lib/python3.13/site-packages/google/protobuf/internal/well_known_types.py:195: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self.FromDatetime(datetime.datetime.utcnow())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[36m[1m======================== short test summary info =========================[0m
[31mERROR[0m test_data.py - NameError: name 'logging' is not defined. Did you forget to import 'logging'?
!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!
[31m====================== [33m4 warnings[0m, [31m[1m1 error[0m[31m in 0.54s[0m[31m ======================[0m
